### ISSUE TITLE
Should Condition to check for MOBI book files be expanded?

### ISSUE THREAD

**Issue by erwin** [paoloap/zaread#17]
For .mobi files, the value returned by `file --mime-type` could be:

* application/octet-stream
* application/x-mobipocket-ebook 

Right now the condition to check if it's a mobi file is only searching for the first possibility:

```
elif [ "$file_mt" = "application/octet-stream" ] && expr "$file" : "^.*\.mobi$" 1>/dev/null  ; then
```

https://github.com/paoloap/zaread/blob/86e148e09e4d2477d18feef2656f01b06b60dc5a/zaread#L98

Just for a quick fix, I simply changed it to search for `x-mobipocket-ebook` and otherwise it works fine now.

**Comment by AlfredEVOL** [comment]
Could u raise a PR for the change. Also it would be better if we checked both cases instead of using a wildcard.

**Comment by iuliandita** [comment]
`application/x-mobipocket-ebook` support has been added with the latest changes.
