### ISSUE TITLE
Rewrite makefile to allow install in $HOME

### ISSUE THREAD

**Issue by Eloitor** [paoloap/zaread#24]
For a local install of zaread, the binary should go to `$HOME/.local/bin`
and the desktop file should go to `$HOME/.local/share/applications`

The current variables in the `Makefile` do not allow this.

**Comment by baleksa** [comment]
Are changes in #19 enough to enable that?

**Comment by Eloitor** [comment]
I think so, thanks!

**Comment by iuliandita** [comment]
#19 merged, we can close this issue.
